// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAueiZSmlPgTIymllehFhxKkS_kOalLXvM',
    appId: '1:703327265743:web:503a57512d93b72913e8ba',
    messagingSenderId: '703327265743',
    projectId: 'credit-card-scanner-project',
    authDomain: 'credit-card-scanner-project.firebaseapp.com',
    storageBucket: 'credit-card-scanner-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9G8DXsXAZVv0FFb2Ph9Prk_qvCXlSoo',
    appId: '1:703327265743:android:c07804e407291fb813e8ba',
    messagingSenderId: '703327265743',
    projectId: 'credit-card-scanner-project',
    storageBucket: 'credit-card-scanner-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCvpXH8wZjlWSuL9Ey9CxkVWBnDuniErw',
    appId: '1:703327265743:ios:f54aaf4ef6cac00e13e8ba',
    messagingSenderId: '703327265743',
    projectId: 'credit-card-scanner-project',
    storageBucket: 'credit-card-scanner-project.appspot.com',
    iosBundleId: 'com.project.creditcardscanner.creditCardScannerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCvpXH8wZjlWSuL9Ey9CxkVWBnDuniErw',
    appId: '1:703327265743:ios:f54aaf4ef6cac00e13e8ba',
    messagingSenderId: '703327265743',
    projectId: 'credit-card-scanner-project',
    storageBucket: 'credit-card-scanner-project.appspot.com',
    iosBundleId: 'com.project.creditcardscanner.creditCardScannerProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAueiZSmlPgTIymllehFhxKkS_kOalLXvM',
    appId: '1:703327265743:web:dffc74676e1007ec13e8ba',
    messagingSenderId: '703327265743',
    projectId: 'credit-card-scanner-project',
    authDomain: 'credit-card-scanner-project.firebaseapp.com',
    storageBucket: 'credit-card-scanner-project.appspot.com',
  );
}
